/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas1
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MESASButton = new javax.swing.JButton();
        PARALLEVARButton = new javax.swing.JButton();
        DELIVERYButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MESAjPanel2 = new javax.swing.JPanel();
        MESA2Button = new javax.swing.JButton();
        MESAjPanel1 = new javax.swing.JPanel();
        MESA1Button = new javax.swing.JButton();
        MESAjPanel3 = new javax.swing.JPanel();
        MESA3Button = new javax.swing.JButton();
        MESAjPanel5 = new javax.swing.JPanel();
        MESA5Button = new javax.swing.JButton();
        MESAjPanel4 = new javax.swing.JPanel();
        MESA4Button = new javax.swing.JButton();
        MESAjPanel7 = new javax.swing.JPanel();
        MESA7Button = new javax.swing.JButton();
        MESAjPanel6 = new javax.swing.JPanel();
        MESA6Button = new javax.swing.JButton();
        MESAjPanel8 = new javax.swing.JPanel();
        MESA8Button = new javax.swing.JButton();
        UNIRMESASButton = new javax.swing.JButton();
        TRANSFERIRMESASBoton = new javax.swing.JButton();
        FinalizarTurnoBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MESASButton.setText("MESAS");

        PARALLEVARButton.setText("PARA LLEVAR");

        DELIVERYButton.setText("DELIVERY");

        jLabel1.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        jLabel1.setText("MESAS");

        MESAjPanel2.setBackground(new java.awt.Color(204, 204, 204));

        MESA2Button.setText("MESA 2");

        javax.swing.GroupLayout MESAjPanel2Layout = new javax.swing.GroupLayout(MESAjPanel2);
        MESAjPanel2.setLayout(MESAjPanel2Layout);
        MESAjPanel2Layout.setHorizontalGroup(
            MESAjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MESA2Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MESAjPanel2Layout.setVerticalGroup(
            MESAjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MESA2Button)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        MESAjPanel1.setBackground(new java.awt.Color(204, 204, 204));

        MESA1Button.setText("MESA 1");

        javax.swing.GroupLayout MESAjPanel1Layout = new javax.swing.GroupLayout(MESAjPanel1);
        MESAjPanel1.setLayout(MESAjPanel1Layout);
        MESAjPanel1Layout.setHorizontalGroup(
            MESAjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MESA1Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MESAjPanel1Layout.setVerticalGroup(
            MESAjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(MESA1Button)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        MESAjPanel3.setBackground(new java.awt.Color(204, 204, 204));

        MESA3Button.setText("MESA 3");
        MESA3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MESA3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MESAjPanel3Layout = new javax.swing.GroupLayout(MESAjPanel3);
        MESAjPanel3.setLayout(MESAjPanel3Layout);
        MESAjPanel3Layout.setHorizontalGroup(
            MESAjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MESA3Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MESAjPanel3Layout.setVerticalGroup(
            MESAjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MESA3Button)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        MESAjPanel5.setBackground(new java.awt.Color(204, 204, 204));

        MESA5Button.setText("MESA 5");
        MESA5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MESA5ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MESAjPanel5Layout = new javax.swing.GroupLayout(MESAjPanel5);
        MESAjPanel5.setLayout(MESAjPanel5Layout);
        MESAjPanel5Layout.setHorizontalGroup(
            MESAjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MESAjPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MESA5Button)
                .addContainerGap())
        );
        MESAjPanel5Layout.setVerticalGroup(
            MESAjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MESA5Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MESAjPanel4.setBackground(new java.awt.Color(204, 204, 204));

        MESA4Button.setText("MESA 4");

        javax.swing.GroupLayout MESAjPanel4Layout = new javax.swing.GroupLayout(MESAjPanel4);
        MESAjPanel4.setLayout(MESAjPanel4Layout);
        MESAjPanel4Layout.setHorizontalGroup(
            MESAjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MESA4Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MESAjPanel4Layout.setVerticalGroup(
            MESAjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MESA4Button)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        MESAjPanel7.setBackground(new java.awt.Color(204, 204, 204));

        MESA7Button.setText("MESA 7");

        javax.swing.GroupLayout MESAjPanel7Layout = new javax.swing.GroupLayout(MESAjPanel7);
        MESAjPanel7.setLayout(MESAjPanel7Layout);
        MESAjPanel7Layout.setHorizontalGroup(
            MESAjPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MESAjPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MESA7Button)
                .addContainerGap())
        );
        MESAjPanel7Layout.setVerticalGroup(
            MESAjPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MESA7Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MESAjPanel6.setBackground(new java.awt.Color(204, 204, 204));

        MESA6Button.setText("MESA 6");

        javax.swing.GroupLayout MESAjPanel6Layout = new javax.swing.GroupLayout(MESAjPanel6);
        MESAjPanel6.setLayout(MESAjPanel6Layout);
        MESAjPanel6Layout.setHorizontalGroup(
            MESAjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MESAjPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MESA6Button)
                .addContainerGap())
        );
        MESAjPanel6Layout.setVerticalGroup(
            MESAjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MESA6Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MESAjPanel8.setBackground(new java.awt.Color(204, 204, 204));

        MESA8Button.setText("MESA 8");

        javax.swing.GroupLayout MESAjPanel8Layout = new javax.swing.GroupLayout(MESAjPanel8);
        MESAjPanel8.setLayout(MESAjPanel8Layout);
        MESAjPanel8Layout.setHorizontalGroup(
            MESAjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MESAjPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MESA8Button)
                .addContainerGap())
        );
        MESAjPanel8Layout.setVerticalGroup(
            MESAjPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MESAjPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MESA8Button)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        UNIRMESASButton.setText("UNIR MESAS");

        TRANSFERIRMESASBoton.setText("TRANSFERIR MESAS");

        FinalizarTurnoBoton.setText("FINALIZAR TURNO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(MESASButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(PARALLEVARButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)
                        .addComponent(DELIVERYButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UNIRMESASButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TRANSFERIRMESASBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FinalizarTurnoBoton)))))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MESAjPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MESAjPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MESAjPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MESAjPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MESASButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PARALLEVARButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELIVERYButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MESAjPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MESAjPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MESAjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MESAjPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MESAjPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MESAjPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(UNIRMESASButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TRANSFERIRMESASBoton)
                    .addComponent(FinalizarTurnoBoton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MESA3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MESA3ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MESA3ButtonActionPerformed

    private void MESA5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MESA5ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MESA5ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELIVERYButton;
    private javax.swing.JButton FinalizarTurnoBoton;
    private javax.swing.JButton MESA1Button;
    private javax.swing.JButton MESA2Button;
    private javax.swing.JButton MESA3Button;
    private javax.swing.JButton MESA4Button;
    private javax.swing.JButton MESA5Button;
    private javax.swing.JButton MESA6Button;
    private javax.swing.JButton MESA7Button;
    private javax.swing.JButton MESA8Button;
    private javax.swing.JButton MESASButton;
    private javax.swing.JPanel MESAjPanel1;
    private javax.swing.JPanel MESAjPanel2;
    private javax.swing.JPanel MESAjPanel3;
    private javax.swing.JPanel MESAjPanel4;
    private javax.swing.JPanel MESAjPanel5;
    private javax.swing.JPanel MESAjPanel6;
    private javax.swing.JPanel MESAjPanel7;
    private javax.swing.JPanel MESAjPanel8;
    private javax.swing.JButton PARALLEVARButton;
    private javax.swing.JButton TRANSFERIRMESASBoton;
    private javax.swing.JButton UNIRMESASButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
