/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author enman
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonMesa = new javax.swing.JButton();
        jButtonParaLlevar = new javax.swing.JButton();
        jButtonDelivery = new javax.swing.JButton();
        jButtonUnirMesas = new javax.swing.JButton();
        jButtonTransferirMesas = new javax.swing.JButton();
        jButtonFinalizarTurno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMesa.setBackground(new java.awt.Color(51, 51, 51));
        jButtonMesa.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButtonMesa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMesa.setText("MESAS");
        jButtonMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 103, 35));

        jButtonParaLlevar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonParaLlevar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButtonParaLlevar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonParaLlevar.setText("PARA LLEVAR");
        jPanel1.add(jButtonParaLlevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 35));

        jButtonDelivery.setBackground(new java.awt.Color(51, 51, 51));
        jButtonDelivery.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButtonDelivery.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelivery.setText("DELIVERY");
        jPanel1.add(jButtonDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, 35));

        jButtonUnirMesas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonUnirMesas.setText("Unir mesas");
        jPanel1.add(jButtonUnirMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jButtonTransferirMesas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonTransferirMesas.setText("Transferir mesas");
        jPanel1.add(jButtonTransferirMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jButtonFinalizarTurno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonFinalizarTurno.setText("Finalizar turno");
        jPanel1.add(jButtonFinalizarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("MESAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 80, 30));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Mesa 1");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Mesa 2");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("Mesa 3");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setText("Mesa 4");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton11.setText("Mesa 5");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton12.setText("Mesa 6");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton13.setText("Mesa 7");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton14.setText("Mesa 8");
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton15.setText("Mesa 9");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton16.setText("Mesa 10");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton17.setText("Mesa 11");
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton18.setText("Mesa 12");
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDelivery;
    private javax.swing.JButton jButtonFinalizarTurno;
    private javax.swing.JButton jButtonMesa;
    private javax.swing.JButton jButtonParaLlevar;
    private javax.swing.JButton jButtonTransferirMesas;
    private javax.swing.JButton jButtonUnirMesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
