/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import ConexionSQL.Conexion;
import Controlador.ProductoCont;
import DAO.ProductoDAO;
import Modelo.Producto;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enman
 */
public class Almacen extends javax.swing.JPanel {

    /**
     * Creates new form DosAlm
     */
    private ProductoDAO productoDAO; // Asegúrate de tener tu ProductoDAO
    private Conexion conexion;
    public Almacen() {
        initComponents();
        conexion = new Conexion();  // Inicializamos la conexión
        productoDAO = new ProductoDAO(conexion.Conectar());  // Creamos el ProductoDAO con la conexión
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textBuscar = new javax.swing.JTextField();
        jButtonBuacar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jButtonImprimirListado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonNuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));

        jButtonBuacar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBuacar.setText("Buscar");
        jButtonBuacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuacarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButtonModificar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jButtonEliminar.setBackground(new java.awt.Color(255, 102, 102));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("LISTA DEL ALMACEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Costo", "Fecha", "Cantidad", "Tipo Movimiento"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 800, 260));

        jButtonImprimirListado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonImprimirListado.setText("Imprimir listado");
        jPanel1.add(jButtonImprimirListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRACION DEL ALMACEN");

        jButtonNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                .addComponent(jButtonNuevo)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonNuevo)
                    .addComponent(jLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 850, 60));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 820, 280));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuacarActionPerformed
        buscar();
    }//GEN-LAST:event_jButtonBuacarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        ReProducto xd = new ReProducto();
        xd.setVisible(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
       //modificar();
    }//GEN-LAST:event_jButtonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuacar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonImprimirListado;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables
    private void cargarDatos() {
        ProductoCont controlador = new ProductoCont(productoDAO, tblProductos);
        controlador.cargarProductos();
    }

    private void eliminar() {
        int rowIndex = tblProductos.getSelectedRow(); 
        if (rowIndex >= 0) {
            int idProducto = (int) tblProductos.getValueAt(rowIndex, 0); 
            ProductoDAO dao = new ProductoDAO(conexion.Conectar());
            dao.eliminarProducto(idProducto);  
            DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
            modelo.removeRow(rowIndex);  
            tblProductos.revalidate();
            tblProductos.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para eliminar.");
        }
    }

    private void buscar() {
       String searchTerm = textBuscar.getText().trim();  // Obtenemos el texto de búsqueda
    
    if (!searchTerm.isEmpty()) {
        ProductoDAO dao = new ProductoDAO(conexion.Conectar());
        ArrayList<Producto> productosEncontrados = dao.buscarProductos(searchTerm);  // Llama a la búsqueda
        
        // Limpia la tabla antes de agregar los resultados de la búsqueda
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0);  // Limpia la tabla

        // Agrega las filas de los productos encontrados
        for (Producto p : productosEncontrados) {
            modelo.addRow(new Object[]{
                p.getIdproducto(),
                p.getNombre(),
                p.getPrecio(),
                p.getStockAct(),
                p.getStockMin(),
                p.getUnidadMedida(),
                p.getDescripcion(),
                p.getCategoria().getIdcategoria()
            });
        }

        // Refresca la tabla para mostrar los resultados
        tblProductos.revalidate();
        tblProductos.repaint();
    } else {
        JOptionPane.showMessageDialog(this, "Por favor ingrese un término de búsqueda.");
    }
    }
}
