/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import VISTA.PanelCentralDeVentas;
import Vista.UsAdm;
import java.awt.BorderLayout;
import java.sql.SQLException;
import javax.swing.JPanel;

/**
 *
 * @author JOSEPH ROJAS
 */
public class Menu extends javax.swing.JFrame {


    public Menu() {
    initComponents();
    this.setLocationRelativeTo(null);
        }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnInicio = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        BtnProveedor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnUsuario = new javax.swing.JButton();
        BtnAlmacen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cont = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnInicio.setBackground(new java.awt.Color(153, 153, 153));
        BtnInicio.setText("Inicio");
        BtnInicio.setBorder(null);
        BtnInicio.setBorderPainted(false);
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 44));

        btnVentas.setBackground(new java.awt.Color(153, 153, 153));
        btnVentas.setText("Ventas");
        btnVentas.setBorder(null);
        btnVentas.setBorderPainted(false);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 40));

        BtnProveedor.setBackground(new java.awt.Color(153, 153, 153));
        BtnProveedor.setText("Proveedor");
        BtnProveedor.setBorder(null);
        BtnProveedor.setBorderPainted(false);
        BtnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(BtnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 44));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/pngwing.com (5).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, 50, 50));

        BtnUsuario.setBackground(new java.awt.Color(153, 153, 153));
        BtnUsuario.setText("Usuario");
        BtnUsuario.setBorder(null);
        BtnUsuario.setBorderPainted(false);
        BtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 190, 44));

        BtnAlmacen.setBackground(new java.awt.Color(153, 153, 153));
        BtnAlmacen.setText("Almacen ");
        BtnAlmacen.setBorder(null);
        BtnAlmacen.setBorderPainted(false);
        BtnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 190, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 860));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, -5, 860, 90));

        cont.setBackground(new java.awt.Color(255, 255, 255));
        cont.setName(""); // NOI18N
        cont.setPreferredSize(new java.awt.Dimension(690, 360));

        javax.swing.GroupLayout contLayout = new javax.swing.GroupLayout(cont);
        cont.setLayout(contLayout);
        contLayout.setHorizontalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        contLayout.setVerticalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        getContentPane().add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 860, 780));
        cont.getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        int usuarioActualId = Seguridad.Sesion.getUsuarioActual().getId_usuario();
    ShowJpanel(new PanelCentralDeVentas());
    }//GEN-LAST:event_btnVentasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        ShowJpanel(new Inicio());
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void BtnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProveedorActionPerformed
        ShowJpanel(new Proveedor());
    }//GEN-LAST:event_BtnProveedorActionPerformed

    private void BtnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlmacenActionPerformed
        ShowJpanel(new Almacen());
    }//GEN-LAST:event_BtnAlmacenActionPerformed

    private void BtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarioActionPerformed
        ShowJpanel(new UsAdm());
    }//GEN-LAST:event_BtnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        new Menu().setVisible(true); // Cambia el 1 por el ID real del usuario
    });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlmacen;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JButton BtnProveedor;
    private javax.swing.JButton BtnUsuario;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel cont;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
  private void ShowJpanel(JPanel p) {
        p.setSize(1280, 820);
        p.setLocation(0, 0);

        cont.removeAll();
        cont.add(p, BorderLayout.CENTER);
        cont.revalidate();
        cont.repaint();

    }
}
