/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.sql.SQLException;
import ConexionSQL.Conexion;
import Controlador.ProveedorCont;
import DAO.ProveedorDAO;
import javax.swing.JOptionPane;
import Modelo.Proveedor;
/**
 *
 * @author enman
 */
public class RegistroCl extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCl
     */
    private ProveedorDAO proveedorDAO; 
    private Conexion conexion;
    public RegistroCl() {
        initComponents();
        //conexion = new Conexion();  
        //proveedorDAO = new ProveedorDAO(conexion.Conectar());
        //ProveedorCont controlador = new ProveedorCont(proveedorDAO, tblproveedor);
        //controlador.cargarProveedores();//*
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproveedor = new javax.swing.JTable();
        jButtonModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgreProve = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblproveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_proveedor", "N° documento", "Nombre", "Apellido", "E-mail", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tblproveedor);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 320));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 340));

        jButtonModificar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(82, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(82, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(82, 23));
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, 30));

        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jPanel2.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel2.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Proveedor");

        btnAgreProve.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgreProve.setText("Nuevo");
        btnAgreProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreProveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                .addComponent(btnAgreProve, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAgreProve))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void btnAgreProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreProveActionPerformed
        RegistroProveedor pro = new RegistroProveedor();
        pro.setVisible(true);
    }//GEN-LAST:event_btnAgreProveActionPerformed
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        eliminarProveedor();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgreProve;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproveedor;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables

    private void cargarProveedores() {
        Conexion conexion =  new Conexion();
        ProveedorDAO proveedorDAO = new ProveedorDAO(conexion.Conectar());
        ProveedorCont controlador =  new ProveedorCont(proveedorDAO, tblproveedor);
        controlador.cargarProveedores();
    }
    private Proveedor obtenerProveedorSeleccionado() {
    int fila = tblproveedor.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un proveedor de la tabla.");
        return null;
    }

    int id = Integer.parseInt(tblproveedor.getValueAt(fila, 0).toString());
    String numeroDocumento = tblproveedor.getValueAt(fila, 1).toString();
    String nombre = tblproveedor.getValueAt(fila, 2).toString();
    String apellido = tblproveedor.getValueAt(fila, 3).toString();
    String telefono = tblproveedor.getValueAt(fila, 4).toString();
    String email = tblproveedor.getValueAt(fila, 5).toString();
    String direccion = tblproveedor.getValueAt(fila, 6).toString();

    Proveedor proveedor = new Proveedor(numeroDocumento, nombre, apellido, telefono, email, direccion);
    proveedor.setid_proveedor(id);
    
    return proveedor;
    }
    private void eliminarProveedor() {
    Proveedor proveedor = obtenerProveedorSeleccionado();
    if (proveedor == null) return;

    int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este proveedor?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            proveedorDAO.eliminarProveedor(proveedor.getid_proveedor());
            JOptionPane.showMessageDialog(this, "Proveedor eliminado.");
            cargarProveedores(); // Refresca la tabla
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }
}

}
