/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import DAO.DashboardDAO;
import Utils.SimpleBarChart;
import Utils.SimpleLineChart;
import Utils.SimplePieChart;
import Utils.IndicatorPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.Map;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.Timer;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author enman
 */
public class Reporte extends javax.swing.JPanel {
    
    private DashboardDAO dashboardDAO;
    private Timer refreshTimer;

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        // Inicializar componentes de NetBeans primero
        initComponents();
        
        // Luego configurar el dashboard
        initializeDashboardSafely();
    }
    
    private void initializeDashboardSafely() {
        try {
            System.out.println("Iniciando conexión a base de datos...");
            dashboardDAO = new DashboardDAO();
            
            System.out.println("Configurando layout del dashboard...");
            setupDashboardLayout();
            
            System.out.println("Forzando tamaños de paneles...");
            forceChartPanelSizes();
            
            // MODO DE PRUEBA: Activar para probar visibilidad de paneles
            boolean modoDebug = false; // Cambiar a false cuando funcione
            
            if (modoDebug) {
                System.out.println("🧪 MODO DEBUG ACTIVADO - Probando visibilidad...");
                testPanelVisibility();
                
                // Esperar 3 segundos y luego cargar gráficos reales
                Timer delayTimer = new Timer(3000, e -> {
                    System.out.println("🔄 Cargando gráficos reales...");
                    loadSampleDataIfEmpty();
                    initializeDashboard();
                    ((Timer)e.getSource()).stop();
                });
                delayTimer.setRepeats(false);
                delayTimer.start();
            } else {
                System.out.println("Cargando datos del dashboard...");
                loadSampleDataIfEmpty();
                initializeDashboard();
            }
            
            System.out.println("Iniciando actualización automática...");
            startAutoRefresh();
            
            System.out.println("✅ Dashboard inicializado correctamente");
            
        } catch (Exception e) {
            System.err.println("❌ Error inicializando dashboard: " + e.getMessage());
            handleDashboardError("inicialización", e);
            
            // Mostrar datos por defecto
            showDefaultData();
        }
    }
    
    private void showDefaultData() {
        // Mostrar datos por defecto si hay error de conexión
        jLabel6.setText("S/ 0.00");
        jLabel7.setText("0");
        jLabel8.setText("0");
        jLabel9.setText("0");
        jTextField1.setText("⚠️ Error de conexión");
        jTextField2.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reporte General de las Ventas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("VENTAS HOY");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel3.setText("PEDIDOS ACTIVOS");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("MESAS OCUPADAS");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("STOCK CRITICO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 990, 200));

        jLabel10.setText("VENTAS ULTIMOS 7 DIAS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel10)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 330, 200));

        jLabel11.setText("PRODUCTOS MAS VENDIDOS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(92, 92, 92))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 360, 200));

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Tipo", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setText("ULTIMOS PEDIDOS");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel12))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 990, 240));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setText("Usuario:");

        jTextField1.setText("jTextField1");

        jLabel14.setText("Hora:");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 990, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 780));
    }// </editor-fold>//GEN-END:initComponents

    // Métodos para el dashboard
    private void initializeDashboard() {
        updateIndicadores();
        updateCharts();
        updateTabla();
        updateUserInfo();
        loadSampleDataIfEmpty(); // Cargar datos de ejemplo si es necesario
    }
    
    private void updateIndicadores() {
        try {
            // Actualizar indicadores principales con mejor formato
            double ventasHoy = dashboardDAO.getVentasHoy();
            int pedidosActivos = dashboardDAO.getPedidosActivos();
            int mesasOcupadas = dashboardDAO.getMesasOcupadas();
            int stockCritico = dashboardDAO.getStockCritico();
            
            // Actualizar valores
            jLabel6.setText(String.format("S/ %.2f", ventasHoy));
            jLabel7.setText(String.valueOf(pedidosActivos));
            jLabel8.setText(String.valueOf(mesasOcupadas));
            jLabel9.setText(String.valueOf(stockCritico));
            
            // Configurar estilos de las etiquetas
            jLabel6.setFont(new Font("Arial", Font.BOLD, 19));
            jLabel6.setForeground(Color.WHITE);
            
            jLabel7.setFont(new Font("Arial", Font.BOLD, 19));
            jLabel7.setForeground(Color.WHITE);
            
            jLabel8.setFont(new Font("Arial", Font.BOLD, 19));
            jLabel8.setForeground(Color.WHITE);
            
            jLabel9.setFont(new Font("Arial", Font.BOLD, 19));
            
            // Cambiar colores según valores críticos para stock
            if (stockCritico > 5) {
                jLabel9.setForeground(Color.RED);
                jPanel6.setBackground(new Color(255, 200, 200));
            } else if (stockCritico > 0) {
                jLabel9.setForeground(new Color(255, 140, 0));
                jPanel6.setBackground(new Color(255, 235, 200));
            } else {
                jLabel9.setForeground(Color.WHITE);
                jPanel6.setBackground(new Color(46, 204, 113)); // Verde
            }
            
            // Configurar colores de fondo de los otros paneles
            jPanel3.setBackground(new Color(52, 152, 219)); // Azul para ventas
            jPanel4.setBackground(new Color(155, 89, 182)); // Púrpura para pedidos
            jPanel5.setBackground(new Color(52, 73, 94));   // Gris azulado para mesas
            
        } catch (Exception e) {
            System.err.println("Error al actualizar indicadores: " + e.getMessage());
            // Mostrar valores por defecto en caso de error
            jLabel6.setText("S/ 0.00");
            jLabel7.setText("0");
            jLabel8.setText("0");
            jLabel9.setText("0");
        }
    }
    
    private void updateCharts() {
        try {
            System.out.println("🔄 Actualizando gráficos con diseño mejorado...");
            
            // 1. Gráfico de ventas de últimos 7 días (línea)
            Map<String, Double> ventasData = dashboardDAO.getVentasUltimos7Dias();
            System.out.println("📊 Datos de ventas obtenidos: " + ventasData.size() + " entradas");
            
            if (!ventasData.isEmpty()) {
                SimpleLineChart ventasChart = new SimpleLineChart(ventasData, "💰 Ventas Últimos 7 Días");
                ventasChart.setLineColor(new Color(52, 152, 219)); // Azul moderno
                
                // Configurar panel9 con mejor diseño
                jPanel9.removeAll();
                jPanel9.setLayout(new BorderLayout());
                jPanel9.setBackground(new Color(248, 249, 250));
                jPanel9.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)
                ));
                
                jPanel9.add(ventasChart, BorderLayout.CENTER);
                jPanel9.setVisible(true);
                
                System.out.println("✅ Gráfico de ventas configurado con diseño mejorado");
            } else {
                showStyledErrorInPanel(jPanel9, "📊 Sin datos de ventas", new Color(52, 152, 219));
            }
            
            // Ocultar la etiqueta original si existe
            if (jLabel10 != null) {
                jLabel10.setVisible(false);
            }
            
            // 2. Gráfico de productos más vendidos (barras)
            Map<String, Integer> productosData = dashboardDAO.getProductosMasVendidos();
            System.out.println("📊 Datos de productos obtenidos: " + productosData.size() + " entradas");
            
            if (!productosData.isEmpty()) {
                SimpleBarChart productosChart = new SimpleBarChart(productosData, "🏆 Productos Más Vendidos");
                productosChart.setBarColor(new Color(46, 204, 113)); // Verde moderno
                
                // Configurar panel10 con mejor diseño
                jPanel10.removeAll();
                jPanel10.setLayout(new BorderLayout());
                jPanel10.setBackground(new Color(248, 249, 250));
                jPanel10.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)
                ));
                
                jPanel10.add(productosChart, BorderLayout.CENTER);
                jPanel10.setVisible(true);
                
                System.out.println("✅ Gráfico de productos configurado con diseño mejorado");
            } else {
                showStyledErrorInPanel(jPanel10, "📊 Sin datos de productos", new Color(46, 204, 113));
            }
            
            // Ocultar la etiqueta original si existe
            if (jLabel11 != null) {
                jLabel11.setVisible(false);
            }
            
            // Forzar actualización visual con animación suave
            SwingUtilities.invokeLater(() -> {
                jPanel9.revalidate();
                jPanel9.repaint();
                jPanel10.revalidate();
                jPanel10.repaint();
                this.revalidate();
                this.repaint();
            });
            
            System.out.println("✅ Gráficos actualizados con diseño moderno y repintados correctamente");
            
        } catch (Exception e) {
            System.err.println("❌ Error actualizando gráficos: " + e.getMessage());
            e.printStackTrace();
            
            // Mostrar mensaje de error estilizado en los paneles
            showStyledErrorInPanel(jPanel9, "❌ Error cargando gráfico de ventas", Color.RED);
            showStyledErrorInPanel(jPanel10, "❌ Error cargando gráfico de productos", Color.RED);
        }
    }
    
    private void updateIndicatorPanelsWithCharts() {
        // Solo actualizar algunos paneles si hay datos suficientes
        try {
            // Panel 3: Mantener indicador de ventas pero mejorado
            double ventasHoy = dashboardDAO.getVentasHoy();
            jLabel6.setText(String.format("S/ %.2f", ventasHoy));
            jLabel6.setFont(new Font("Arial", Font.BOLD, 16));
            
            // Panel 4: Mantener indicador de pedidos
            int pedidosActivos = dashboardDAO.getPedidosActivos();
            jLabel7.setText(String.valueOf(pedidosActivos));
            jLabel7.setFont(new Font("Arial", Font.BOLD, 16));
            
            // Panel 5: Mantener indicador de mesas
            int mesasOcupadas = dashboardDAO.getMesasOcupadas();
            jLabel8.setText(String.valueOf(mesasOcupadas));
            jLabel8.setFont(new Font("Arial", Font.BOLD, 16));
            
            // Panel 6: Stock crítico con color de alerta
            int stockCritico = dashboardDAO.getStockCritico();
            jLabel9.setText(String.valueOf(stockCritico));
            jLabel9.setFont(new Font("Arial", Font.BOLD, 16));
            
            // Cambiar color según stock crítico
            if (stockCritico > 5) {
                jLabel9.setForeground(new Color(231, 76, 60)); // Rojo
                jPanel6.setBackground(new Color(255, 230, 230));
            } else if (stockCritico > 0) {
                jLabel9.setForeground(new Color(243, 156, 18)); // Naranja
                jPanel6.setBackground(new Color(255, 248, 230));
            } else {
                jLabel9.setForeground(new Color(39, 174, 96)); // Verde
                jPanel6.setBackground(new Color(230, 255, 230));
            }
            
        } catch (Exception e) {
            System.err.println("Error actualizando indicadores: " + e.getMessage());
        }
    }
    
    private void updateTabla() {
        // Actualizar tabla de últimos pedidos con más información
        List<Map<String, Object>> pedidos = dashboardDAO.getUltimosPedidos();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // Configurar columnas de la tabla
        String[] columnNames = {"ID", "Cliente", "Tipo", "Estado", "Fecha"};
        model.setColumnIdentifiers(columnNames);
        model.setRowCount(0); // Limpiar tabla
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM HH:mm");
        
        for (Map<String, Object> pedido : pedidos) {
            Object[] row = new Object[5];
            row[0] = pedido.get("id");
            row[1] = pedido.get("cliente") != null ? pedido.get("cliente") : "Cliente General";
            row[2] = formatTipoPedido((String) pedido.get("tipo"));
            row[3] = formatEstadoPedido((String) pedido.get("estado"));
            row[4] = pedido.get("fecha") != null ? sdf.format(pedido.get("fecha")) : "";
            model.addRow(row);
        }
        
        // Personalizar la apariencia de la tabla
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setBackground(new Color(102, 102, 102));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        
        // Agregar información adicional de productos con bajo stock en una segunda vista
        addStockAlerts();
    }
    
    private String formatTipoPedido(String tipo) {
        if (tipo == null) return "N/A";
        switch (tipo.toLowerCase()) {
            case "delivery": return "Delivery";
            case "para_llevar": 
            case "llevar": return "Para Llevar";
            default: return tipo;
        }
    }
    
    private String formatEstadoPedido(String estado) {
        if (estado == null) return "N/A";
        switch (estado.toLowerCase()) {
            case "pendiente": return "⏳ Pendiente";
            case "en_preparacion": return "👨‍🍳 En Preparación";
            case "en_camino": return "🚗 En Camino";
            case "entregado": return "✅ Entregado";
            case "cancelado": return "❌ Cancelado";
            default: return estado;
        }
    }
    
    private void addStockAlerts() {
        // Agregar alertas de stock bajo en el área inferior si es necesario
        List<Map<String, Object>> productosStock = dashboardDAO.getProductosBajoStock();
        if (!productosStock.isEmpty()) {
            // Mostrar mensaje de alerta en jTextField1 si hay productos con stock crítico
            jTextField1.setText("⚠️ " + productosStock.size() + " productos con stock bajo");
            jTextField1.setBackground(new Color(255, 235, 205)); // Color de alerta suave
        }
    }
    
    private void updateUserInfo() {
        // Actualizar información del usuario y estadísticas adicionales
        jTextField1.setText("Admin Dashboard"); // Aquí podrías obtener el usuario actual de la sesión
        jTextField2.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date()));
        
        // Agregar estadísticas adicionales en los labels del header
        updateHeaderStats();
    }
    
    private void updateHeaderStats() {
        // Actualizar el título del dashboard con estadísticas en tiempo real
        try {
            int totalClientes = dashboardDAO.getTotalClientes();
            double promedioVenta = dashboardDAO.getPromedioVentaDiaria();
            
            String dashboardTitle = String.format("DASHBOARD - %d Clientes | Promedio Diario: S/ %.2f", 
                                                totalClientes, promedioVenta);
            jLabel1.setText(dashboardTitle);
            jLabel1.setFont(new Font("Arial", Font.BOLD, 16));
        } catch (Exception e) {
            jLabel1.setText("DASHBOARD - El Dorado");
            System.err.println("Error actualizando estadísticas del header: " + e.getMessage());
        }
    }
    
    // Método adicional para mostrar gráficos extra (opcional)
    private void updateAdditionalCharts() {
        // Este método se puede usar para agregar más gráficos en el futuro
        // Por ahora mantener los indicadores principales funcionando
        System.out.println("Gráficos adicionales disponibles para futuras versiones");
    }
    
    private void startAutoRefresh() {
        // Configurar timer para actualización automática cada 30 segundos
        if (refreshTimer != null) {
            refreshTimer.stop();
        }
        
        refreshTimer = new Timer(30000, e -> {
            try {
                System.out.println("🔄 Actualizando dashboard automáticamente...");
                updateIndicadores();
                updateCharts();
                updateTabla();
                updateUserInfo();
            } catch (Exception ex) {
                System.err.println("❌ Error en actualización automática: " + ex.getMessage());
            }
        });
        
        refreshTimer.start();
        System.out.println("⏰ Actualización automática iniciada (cada 30 segundos)");
    }
    
    // Método para detener el timer cuando se cierre el panel
    public void stopRefresh() {
        try {
            if (refreshTimer != null && refreshTimer.isRunning()) {
                refreshTimer.stop();
                System.out.println("Timer de actualización detenido");
            }
            if (dashboardDAO != null) {
                dashboardDAO.cerrarConexion();
                System.out.println("Conexión a base de datos cerrada");
            }
        } catch (Exception e) {
            System.err.println("Error al cerrar recursos: " + e.getMessage());
        }
    }
    
    // Método para actualizar manualmente el dashboard
    public void refreshDashboard() {
        try {
            initializeDashboard();
            System.out.println("Dashboard actualizado manualmente");
        } catch (Exception e) {
            handleDashboardError("actualización manual", e);
        }
    }
    
    // Método para cargar datos de ejemplo si no hay datos en la BD
    private void loadSampleDataIfEmpty() {
        try {
            // Verificar si hay datos reales, si no, usar datos de ejemplo
            Map<String, Double> ventasData = dashboardDAO.getVentasUltimos7Dias();
            if (ventasData.isEmpty()) {
                System.out.println("⚠️ No hay datos de ventas, usando datos de ejemplo");
                // Los datos de ejemplo ya se manejan en DashboardDAO
            }
            
            Map<String, Integer> productosData = dashboardDAO.getProductosMasVendidos();
            if (productosData.isEmpty()) {
                System.out.println("⚠️ No hay datos de productos, usando datos de ejemplo");
                // Los datos de ejemplo ya se manejan en DashboardDAO
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error cargando datos: " + e.getMessage());
        }
    }
    
    // Método mejorado para manejo de errores
    private void handleDashboardError(String operation, Exception e) {
        System.err.println("❌ Error en " + operation + ": " + e.getMessage());
        
        // Mostrar mensaje de error en los componentes principales
        if (jTextField1 != null) {
            jTextField1.setText("⚠️ Error: " + operation);
            jTextField1.setForeground(Color.RED);
        }
        
        // Opcional: mostrar diálogo de error
        // javax.swing.JOptionPane.showMessageDialog(this, 
        //     "Error en dashboard: " + e.getMessage(), 
        //     "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Método para reintentar conexión
    public void retryConnection() {
        try {
            if (dashboardDAO != null) {
                dashboardDAO.cerrarConexion();
            }
            dashboardDAO = new DashboardDAO();
            initializeDashboard();
            startAutoRefresh();
            
            jTextField1.setText("✅ Conexión restaurada");
            jTextField1.setBackground(new Color(200, 255, 200));
        } catch (Exception e) {
            handleDashboardError("reconexión", e);
        }
    }

    // Método para configurar el diseño del dashboard
    private void setupDashboardLayout() {
        // Configurar panel principal con mejor apariencia
        this.setBackground(new Color(236, 240, 241));
        
        // Configurar paneles de gráficos con diseño moderno
        if (jPanel9 != null) {
            jPanel9.setBackground(new Color(248, 249, 250));
            jPanel9.setPreferredSize(new Dimension(300, 200));
            jPanel9.setMinimumSize(new Dimension(280, 190));
            jPanel9.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)
            ));
            System.out.println("✅ jPanel9 configurado con diseño moderno");
        }
        
        if (jPanel10 != null) {
            jPanel10.setBackground(new Color(248, 249, 250));
            jPanel10.setPreferredSize(new Dimension(300, 200));
            jPanel10.setMinimumSize(new Dimension(280, 190));
            jPanel10.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
                BorderFactory.createEmptyBorder(5, 5, 5, 5)
            ));
            System.out.println("✅ jPanel10 configurado con diseño moderno");
        }
        
        // Mejorar el panel de encabezado
        if (jPanel2 != null) {
            jPanel2.setBackground(new Color(44, 62, 80));
            jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 20));
            jLabel1.setForeground(Color.WHITE);
        }
        
        // Mejorar el panel de indicadores
        if (jPanel8 != null) {
            jPanel8.setBackground(new Color(236, 240, 241));
            jPanel8.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        }
        
        // Mejorar la tabla de pedidos
        if (jPanel11 != null) {
            jPanel11.setBackground(new Color(248, 249, 250));
            jPanel11.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
            ));
        }
        
        // Mejorar el panel inferior
        if (jPanel7 != null) {
            jPanel7.setBackground(new Color(52, 73, 94));
            if (jLabel13 != null) jLabel13.setForeground(Color.WHITE);
            if (jLabel14 != null) jLabel14.setForeground(Color.WHITE);
            if (jTextField1 != null) {
                jTextField1.setBackground(new Color(236, 240, 241));
                jTextField1.setBorder(BorderFactory.createLineBorder(new Color(149, 165, 166), 1));
            }
            if (jTextField2 != null) {
                jTextField2.setBackground(new Color(236, 240, 241));
                jTextField2.setBorder(BorderFactory.createLineBorder(new Color(149, 165, 166), 1));
            }
        }
    }
    
    private void forceChartPanelSizes() {
        // Forzar tamaños específicos para los paneles de gráficos
        try {
            if (jPanel9 != null) {
                jPanel9.setSize(280, 190);
                jPanel9.setPreferredSize(new Dimension(280, 190));
                jPanel9.setVisible(true);
                System.out.println("📏 Tamaño de jPanel9 forzado: " + jPanel9.getSize());
            }
            
            if (jPanel10 != null) {
                jPanel10.setSize(280, 190);
                jPanel10.setPreferredSize(new Dimension(280, 190));
                jPanel10.setVisible(true);
                System.out.println("📏 Tamaño de jPanel10 forzado: " + jPanel10.getSize());
            }
            
            // Forzar revalidación del panel principal
            this.revalidate();
            this.repaint();
            
        } catch (Exception e) {
            System.err.println("❌ Error forzando tamaños: " + e.getMessage());
        }
    }
    
    // Método de prueba para verificar visualización de componentes
    private void testPanelVisibility() {
        System.out.println("🧪 Probando visibilidad de paneles...");
        
        // Probar panel9
        if (jPanel9 != null) {
            jPanel9.removeAll();
            jPanel9.setLayout(new BorderLayout());
            jPanel9.setBackground(Color.YELLOW);
            
            javax.swing.JLabel testLabel9 = new javax.swing.JLabel("<html><center>GRÁFICO DE VENTAS<br>Panel funcionando correctamente</center></html>");
            testLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            testLabel9.setFont(new Font("Arial", Font.BOLD, 14));
            testLabel9.setForeground(Color.BLACK);
            
            jPanel9.add(testLabel9, BorderLayout.CENTER);
            jPanel9.revalidate();
            jPanel9.repaint();
            
            System.out.println("✅ jPanel9 configurado con componente de prueba");
        }
        
        // Probar panel10
        if (jPanel10 != null) {
            jPanel10.removeAll();
            jPanel10.setLayout(new BorderLayout());
            jPanel10.setBackground(Color.CYAN);
            
            javax.swing.JLabel testLabel10 = new javax.swing.JLabel("<html><center>GRÁFICO DE PRODUCTOS<br>Panel funcionando correctamente</center></html>");
            testLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            testLabel10.setFont(new Font("Arial", Font.BOLD, 14));
            testLabel10.setForeground(Color.BLACK);
            
            jPanel10.add(testLabel10, BorderLayout.CENTER);
            jPanel10.revalidate();
            jPanel10.repaint();
            
            System.out.println("✅ jPanel10 configurado con componente de prueba");
        }
        
        // Forzar actualización del panel principal
        this.revalidate();
        this.repaint();
        
        System.out.println("🧪 Prueba de visibilidad completada");
    }
    
    private void showErrorInPanel(javax.swing.JPanel panel, String errorMessage) {
        panel.removeAll();
        panel.setLayout(new BorderLayout());
        
        javax.swing.JLabel errorLabel = new javax.swing.JLabel("<html><center>" + errorMessage + "</center></html>");
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setForeground(Color.RED);
        errorLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        
        panel.add(errorLabel, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
    
    private void showStyledErrorInPanel(javax.swing.JPanel panel, String errorMessage, Color themeColor) {
        panel.removeAll();
        panel.setLayout(new BorderLayout());
        panel.setBackground(new Color(248, 249, 250));
        panel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        
        // Panel interno para el mensaje
        javax.swing.JPanel messagePanel = new javax.swing.JPanel(new BorderLayout());
        messagePanel.setBackground(Color.WHITE);
        messagePanel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(themeColor, 2),
            BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));
        
        javax.swing.JLabel errorLabel = new javax.swing.JLabel("<html><center>" + errorMessage + "</center></html>");
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setForeground(themeColor);
        errorLabel.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        messagePanel.add(errorLabel, BorderLayout.CENTER);
        panel.add(messagePanel, BorderLayout.CENTER);
        
        panel.revalidate();
        panel.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
