/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author enman
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMes = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonMesa = new javax.swing.JButton();
        btnLlevar = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMes.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpMesLayout = new javax.swing.GroupLayout(jpMes);
        jpMes.setLayout(jpMesLayout);
        jpMesLayout.setHorizontalGroup(
            jpMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jpMesLayout.setVerticalGroup(
            jpMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        add(jpMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 520));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButtonMesa.setBackground(new java.awt.Color(51, 51, 51));
        jButtonMesa.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButtonMesa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMesa.setText("MESAS");
        jButtonMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesaActionPerformed(evt);
            }
        });

        btnLlevar.setBackground(new java.awt.Color(51, 51, 51));
        btnLlevar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnLlevar.setForeground(new java.awt.Color(255, 255, 255));
        btnLlevar.setText("PARA LLEVAR");
        btnLlevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlevarActionPerformed(evt);
            }
        });

        btnDelivery.setBackground(new java.awt.Color(51, 51, 51));
        btnDelivery.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnDelivery.setForeground(new java.awt.Color(255, 255, 255));
        btnDelivery.setText("DELIVERY");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButtonMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnLlevar)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLlevar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesaActionPerformed
        ShowJpanel(new PruebaVenta());
    }//GEN-LAST:event_jButtonMesaActionPerformed

    private void btnLlevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlevarActionPerformed
        ShowJpanel(new VentaParallevar());
    }//GEN-LAST:event_btnLlevarActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        ShowJpanel(new DeliveryVts());
    }//GEN-LAST:event_btnDeliveryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnLlevar;
    private javax.swing.JButton jButtonMesa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpMes;
    // End of variables declaration//GEN-END:variables
      private void ShowJpanel(JPanel p) {
        p.setSize(1280, 820);
        p.setLocation(0, 0);

        jpMes.removeAll();
        jpMes.add(p, BorderLayout.CENTER);
        jpMes.revalidate();
        jpMes.repaint();

    }
}
